<?php

/**
 * @file
 * Module file for the Memory Limit Policy module.
 */

use Drupal\memory_limit_policy\Entity\MemoryLimitPolicy;

/**
 * Menu argument loader.
 *
 * @param string $id
 *   ID of the memory limit policy entity.
 *
 * @return \Drupal\Core\Entity\EntityInterface
 *   Returns a memory limit policy object.
 */
function memory_limit_policy_load($id) {
  return MemoryLimitPolicy::load($id);
}
