memory_limit_policy.constraint.plugin.role:
  type: memory_limit_policy.constraint.plugin
  mapping:
    roles:
      type: sequence
      label: 'Roles'
      sequence:
        type: string
        label: 'Role'
